### PR TITLE
Add support for node['audit']['profiles'] as a hash of hashes 

### PR DESCRIPTION
**Pull request by mattray**
Policyfiles with includes do not allow merging arrays and it's a bit unclear why an array was chosen. This patch does not change the existing behavior, only supplements it.

Signed-off-by: Matt Ray <matthewhray@gmail.com>

### CODE REVIEW

**Comment by chris-rock** [comment]
@mattray Great work. Should we update the docs to make the hash map the default now? I like the simpler style.

**Comment by mattray** [comment]
Glad you like it, definitely needed it for Policyfiles. We could add deprecation warnings for array-style usage for a few releases just so we don't blindside anyone.

**Comment by chris-rock** [comment]
I agree a deprecation warning would be great. I cannot recall why we went with arrays in the first place, but maps look very nice

**Comment by mattray** [comment]
I've updated the PR with a deprecation warning.

**Comment by jblaine** [comment]
Note https://github.com/chef-cookbooks/audit/issues/339 where hash of hashes, the new hotness being shown as the replacement for the other 2 methods... doesn't actually work.

**Comment by mattray** [comment]
@jblaine here's a working example: 
https://github.com/mattray/home-repo/blob/master/policyfiles/base.rb#L23

**Pull request merged**
