### PR TITLE
convert library resources to proper custom resources

### PR DESCRIPTION
**Pull request by lamont-granquist**
library cookbooks are not a recommended cookbook pattern

see:

https://docs.chef.io/custom_resources_notes.html

and issues like this which are directly related to trying to
fight the resources DSL:

https://github.com/chef-cookbooks/httpd/issues/97

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
bonus: added compat_resource cookbook dep

**Comment by lamont-granquist** [comment]
bonus bonus:  try using a version of berkshelf than is less than a year old

**Comment by lamont-granquist** [comment]
bonus bonus bonus: the Encoding cop is from the ruby-1.8/1.9 era so remove that

**Comment by lamont-granquist** [comment]
@tas50 @iennae okay i think i'm done now.

**Comment by iennae** [comment]
Taking a look ..

**Pull request merged**
