### PR TITLE
Implement an 'audit' reporter that will terminate Chef Client runs on profile failures

### PR DESCRIPTION
**Pull request by sbabcoc**
### Description

This pull request implements an `audit enforcer` reporter to replace the `fail_if_any_audits_failed` feature that was removed a while ago.

### Issues Resolved

[List any existing issues this PR resolves]

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by sbabcoc** [comment]
Looks like the Travis failures were caused by a configuration issue that's been resolved.

**Comment by sbabcoc** [comment]
Given that the purpose of this reporter is to throw an error, I don't know how to implement a test for it.

**Comment by alexpop** [comment]
Thank you Scott for bringing this option back into the audit cookbook.

I pushed a commit to this branch:
https://github.com/chef-cookbooks/audit/commits/pr-380

Can you cherry-pick that into your fork please? It adds unit tests for AuditEnforcer and takes care of lint errors.

**Comment by sbabcoc** [comment]
Merged unit tests and linking fixes from @alexpop

**Comment by sbabcoc** [comment]
The pull request that added the `fail_if_any_audits_failed` feature is here: https://github.com/chef-cookbooks/audit/pull/25
The pull request that removed this feature is here: https://github.com/chef-cookbooks/audit/pull/113

Here's the specific comment:
> jeremymv2 on Oct 19, 2016  Contributor
Since we're moving away from a resource converge I don't think 'fail_if_any_audits_failed' makes sense any more. The original intent was to fail during converge in a pipeline phase such as kitchen converge. Now, with the report handler, we'd rely on kitchen-inspec to reference the profiles and kitchen verify to provide a pass|fail status to the CI framework.

**Comment by sbabcoc** [comment]
As for usefulness, this enables me to terminate a pipeline if a non-compliant node is encountered. The current behavior is to passively report the failure and continue to the next stage, which will then choke because of the previously detected issue.

**Comment by sbabcoc** [comment]
Sorry, it's really easy to close pull requests accidentally in the mobile view of GitHub.

**Comment by sbabcoc** [comment]
@alexpop has been incredibly helpful on this PR! Many thanks!
He discovered that the `audit enforced` raises the error, but the `audit` cookbook is eating the failure. This happens in the `run_report_safely` method, which catches exceptions and only re-throws them if the `fail_if_not_present` attribute is specified. I'll push revisions that will also re-throw for `audit enforcer`.

**Pull request merged**
