### PR TITLE
Update changelog generator task to be native rake task

### PR DESCRIPTION
**Pull request by brentm5**
### Description

This updates the rake task for generating the CHANGELOG documentation so that it includes the new link as well as dynamically gets the current version number.

### Issues Resolved

It solves an issue where the changelog `Full Changelog` link is generated wrong.

### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by chris-rock** [comment]
Great, thanks for the improvement @brentm5

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @brentm5

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chris-rock** [comment]
@brentm5 Have you signed the Chef CLA?

**Comment by brentm5** [comment]
Yeah I recently changed my usename from bigbam505 to brentm5.  Looks like supermarket might have had the old account so I went ahead and reauthorized with the new account.  I assume thats the issue anyway.

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by chris-rock** [comment]
@brentm5 Awesome!

**Pull request merged**
